# -*- coding: utf-8 -*-
"""07-02. LSTM and GRU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwhCDQaCN_PofD9AWtZSsG-ReQrkEdr0
"""

import torch
import torch.nn as nn

torch.__version__

input_dim = 5 # 입력의 크기
hidden_size = 8 # 은닉 상태의 크기

"""## 4. 파이토치의 nn.LSTM()"""

nn.RNN(input_dim, hidden_size, batch_first=True)

nn.LSTM(input_dim, hidden_size, batch_first=True)

"""## 5. GRU(Gated Recurrent Unit)"""

nn.RNN(input_dim, hidden_size, batch_first=True)

nn.GRU(input_dim, hidden_size, batch_first=True)