# -*- coding: utf-8 -*-
"""12-01. one_hot_encoding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gLanEPcYMvOl3IbCFO1J3p3CTTwd9OW
"""

pip install konlpy

"""## 1. 원-핫 인코딩(One-hot encoding)이란?"""

from konlpy.tag import Okt
okt = Okt()
token = okt.morphs("나는 자연어 처리를 배운다")
print(token)

word2index = {}
for voca in token:
     if voca not in word2index.keys():
       word2index[voca] = len(word2index)
print(word2index)

def one_hot_encoding(word, word2index):
    one_hot_vector = [0]*(len(word2index))
    index = word2index[word]
    one_hot_vector[index] = 1
    return one_hot_vector

one_hot_encoding("자연어",word2index)