# -*- coding: utf-8 -*-
"""09-02. text_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJUWQkzJlnYM1vTHAq5X_O3Z-FhVIriz

## 3. 불필요한 단어의 제거
"""

import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('', text))